- name: Create the ohpc-test user on cnodes
  ansible.builtin.user:
    name: ohpc-test
  when:
    - not enable_warewulf
    - inventory_hostname in groups[nt_cnodes]

- name: Create the ohpc-test user on cnodes with warewulf
  ansible.builtin.dnf: "wwsh file resync passwd shadow group ; pdsh -w {{ compute_regex }} /warewulf/bin/wwgetfiles"
  when:
    - inventory_hostname in groups[nt_sms]
    - enable_warewulf

- name: Remove test-suite
  when:
    - inventory_hostname in groups[nt_sms]

  block:
    - name: Uninstall test-suite
      ansible.builtin.dnf:
        name: test-suite-ohpc
        state: absent

    - name: Wipe out anything test-suite related
      ansible.builtin.command: rm -rf /home/ohpc-test/tests

- name: Setup test-suite
  when:
    - inventory_hostname in groups[nt_sms]
    - enable_testsuiteohpc

  block:
    - name: Install test suite
      ansible.builtin.dnf:
        name: test-suite-ohpc
        state: present

    - name: Install TAU for openmpi3 (default is mpich)
      ansible.builtin.dnf:
        name: tau-gnu7-openmpi3-ohpc
        state: present

    - name: Create the ohpc-test user on cnodes
      ansible.builtin.command: "wwsh file resync passwd shadow group ; pdsh -w {{ compute_regex }} /warewulf/bin/wwgetfiles"
      when:
        - enable_warewulf

    - name: Render configure script template
      ansible.builtin.template:
        src: "{{ role_path }}/templates/configure.sh.j2"
        dest: /home/ohpc-test/configure.sh
        group: ohpc-test
        owner: ohpc-test
        mode: '0744'

    - name: Configure test suite
      ansible.builtin.command: /home/ohpc-test/configure.sh
      become: true
      become_user: ohpc-test
      become_method: ansible.builtin.su
      register: testsuite_configure

    - debug: msg="{{ testsuite_configure.stdout_lines }} {{ testsuite_configure.stderr_lines }}"

    - name: Run the test suite with JUnit xml output in addition to regular logs
      ansible.builtin.command: cd /home/ohpc-test/tests && make check
      environment:
        BATS_JUNIT_FORMAT: "1"
      become: true
      become_user: ohpc-test
      become_method: ansible.builtin.su
      register: testsuite_output

    - debug: msg="{{ testsuite_output.stdout_lines }} {{ testsuite_output.stderr_lines }}"

    - name: JUnit logs
      when:
        - enable_junit

      block:
        - name: If we want, get those xml JUnit logs back
          ansible.builtin.find:
            paths: /home/ohpc-test/tests
            recurse: true
            patterns: "*.xml"
          register: xml_junit_files

        - name: Archive all those files
          community.general.archive:
            path: "{{ xml_junit_files.files | map(attribute='path') | list }}"
            dest: "/tmp/junit-results.tar.gz"
            format: gz

        - name: Fetch the archive
          ansible.builtin.fetch:
            src: "/tmp/junit-results.tar.gz"
            dest: "{{ playbook_dir }}/../"
