---

# This file is distributed under the Apache License (the
# "License"); you may not use this file except in compliance
# with the License.  See the LICENSE file distributed with
# this work for additional information regarding copyright
# ownership.
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# This file is derived from recipe.sh in OpenHPC distribution
# and ported by Linaro Ltd. and Fujitsu Ltd.

#
# roles/rsyslog/tasks/main.yml
#

# --------------------------------------------------------
# Configure rsyslog on SMS and computes (Section 3.7.4.10)
# --------------------------------------------------------
- name: Define computing node forwarding destination on a computing node
  ansible.builtin.lineinfile:
    path: "/etc/rsyslog.conf"
    state: present
    backrefs: false
    regexp: '^\*\.\* @{{ sms_ip }}{{ d_colon }}514$'
    line: "*.* @{{ sms_ip }}{{ d_colon }}514"
  when:
    - inventory_hostname in groups[nt_cnodes]
    - not enable_warewulf

- name: Disable most local logging on computes for info on a computing node
  ansible.builtin.replace:
    dest: "/etc/rsyslog.conf"
    regexp: '^\*\.info'
    replace: "#*.info"
    backup: true
  when:
    - inventory_hostname in groups[nt_cnodes]
    - not enable_warewulf

- name: Disable most local logging on computes for authpriv on a computing node
  ansible.builtin.replace:
    dest: "/etc/rsyslog.conf"
    regexp: '^authpriv'
    replace: "#authpriv"
    backup: true
  when:
    - inventory_hostname in groups[nt_cnodes]
    - not enable_warewulf

- name: Disable most local logging on computes for mail on a computing node
  ansible.builtin.replace:
    dest: "/etc/rsyslog.conf"
    regexp: '^mail'
    replace: "#mail"
    backup: true
  when:
    - inventory_hostname in groups[nt_cnodes]
    - not enable_warewulf

- name: Disable most local logging on computes for cron on a computing node
  ansible.builtin.replace:
    dest: "/etc/rsyslog.conf"
    regexp: '^cron'
    replace: "#cron"
    backup: true
  when:
    - inventory_hostname in groups[nt_cnodes]
    - not enable_warewulf

- name: Disable most local logging on computes for uucp on a computing node
  ansible.builtin.replace:
    dest: "/etc/rsyslog.conf"
    regexp: '^uucp'
    replace: "#uucp"
    backup: true
  when:
    - inventory_hostname in groups[nt_cnodes]
    - not enable_warewulf

- name: Configure to receive messages module of rsyslog on a computing node
  ansible.builtin.replace:
    dest: /etc/rsyslog.conf
    regexp: '#\$ModLoad imudp'
    replace: "$ModLoad imudp"
    backup: true
  when:
    ( ( inventory_hostname in groups[nt_sms] ) or
    ( inventory_hostname in groups[nt_devnodes] ) or
    ( inventory_hostname in groups[nt_cnodes] ) ) and ( not enable_warewulf )

- name: Configure to receive messages port for rsyslog on a computing node
  ansible.builtin.replace:
    dest: /etc/rsyslog.conf
    regexp: '#\$UDPServerRun 514'
    replace: "$UDPServerRun 514"
    backup: true
  when:
    ( ( inventory_hostname in groups[nt_sms] ) or
    ( inventory_hostname in groups[nt_devnodes] ) or
    ( inventory_hostname in groups[nt_cnodes] ) ) and ( not enable_warewulf )

- name: Restart rsyslog on a computing node
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  when:
    ( inventory_hostname in groups[nt_sms] ) or
    ( inventory_hostname in groups[nt_devnodes] ) or
    ( ( inventory_hostname in groups[nt_cnodes] ) and ( not enable_warewulf ) )
