---

# This file is distributed under the Apache License (the
# "License"); you may not use this file except in compliance
# with the License.  See the LICENSE file distributed with
# this work for additional information regarding copyright
# ownership.
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# This file is derived from recipe.sh in OpenHPC distribution
# and ported by Linaro Ltd. and Fujitsu Ltd.

#
# roles/third-party-libs-intel/tasks/main.yml
#

# if [[ ${enable_intel_packages} -eq 1 ]];then
- name: Install Development libraries for use with Intel Parallel Studio
  when:
    - enable_intel_packages
  block:
#     yum -y groupinstall ohpc-serial-libs-intel
#     yum -y groupinstall ohpc-io-libs-intel
#     yum -y groupinstall ohpc-perf-tools-intel
#     yum -y groupinstall ohpc-python-libs-intel
#     yum -y groupinstall ohpc-runtimes-intel
    - name: Install Development libraries for use with Intel Parallel Studio on master and a development node
      ansible.builtin.dnf:
        state: present
        name:
          - ohpc-serial-libs-intel
          - ohpc-io-libs-intel
          - ohpc-python-libs-intel
          - ohpc-runtimes-intel
      when:
        ( inventory_hostname in groups[nt_devnodes] ) or
        ( ( inventory_hostname in groups[nt_cnodes] ) and ( not enable_warewulf ) )

    - name: Install Development libraries for use with Intel Parallel Studio for a computing image on master
      ansible.builtin.dnf:
        state: present
        installroot: "{{ compute_chroot_loc }}"
        name:
          - ohpc-serial-libs-intel
          - ohpc-io-libs-intel
          - ohpc-python-libs-intel
          - ohpc-runtimes-intel
      when:
        - inventory_hostname in groups[nt_sms]
        - enable_warewulf
