---

# This file is distributed under the Apache License (the
# "License"); you may not use this file except in compliance
# with the License.  See the LICENSE file distributed with
# this work for additional information regarding copyright
# ownership.
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# This file is derived from recipe.sh in OpenHPC distribution
# and ported by Linaro Ltd. and Fujitsu Ltd.

#
# roles/lmod/tasks/main.yml
#

# yum -y --installroot=$CHROOT install lmod-ohpc
- name: Install lmod-ohpc for computing node images on master
  ansible.builtin..dnf:
    name: lmod-ohpc
    installroot: "{{ compute_chroot_loc }}"
    state: present
  when:
    - inventory_hostname in groups[nt_sms]
    - enable_warewulf

- name: Install lmod-ohpc on a computing node
  ansible.builtin..dnf:
    name: lmod-ohpc
    state: present
  when:
    - inventory_hostname in groups[nt_cnodes]
    - enable_warewulf

# yum -y install lmod-defaults-gnu-mvapich2-ohpc
- name: Install the lmod-defaults package on master and a development node
  ansible.builtin.dnf:
    name: "{{ ohpc_lmod_mpi_default }}"
    state: present
  when:
    ( inventory_hostname in groups[ nt_devnodes ] ) or
    ( ( inventory_hostname in groups[nt_cnodes] ) and ( enable_warewulf ) )

- name: Install the lmod-defaults package for a computing image on master
  ansible.builtin.dnf:
    name: "{{ ohpc_lmod_mpi_default }}"
    installroot: "{{ compute_chroot_loc }}"
    state: present
  when:
    - inventory_hostname in groups[nt_sms]
    - enable_warewulf

- name: Source the lmod-defaults
  ansible.builtin.cmd:
    cmd: "module load ohpc"
  when:
    ( inventory_hostname in groups[ nt_devnodes ] ) or
    ( ( inventory_hostname in groups[nt_cnodes] ) and ( enable_warewulf ) )
