---

# This file is distributed under the Apache License (the
# "License"); you may not use this file except in compliance
# with the License. See the LICENSE file distributed with
# this work for additional information regarding copyright
# ownership.

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# This file is derived from recipe.sh in OpenHPC distribution
# and ported by Linaro Ltd. and Fujitsu Ltd.

#
# roles/nfs/tasks/main.yml
#

# echo "${sms_ip}:/home /home nfs nfsvers=3,rsize=1024,wsize=1024,cto 0 0" >> $CHROOT/etc/fstab
- name: Add NFS client to mount /home on a computing node
  ansible.posix.mount:
    name: "/home"
    src: "{{ sms_ip }}{{ d_colon }}/home"
    fstype: nfs
    opts: "rsize=1024,wsize=1024,cto"
    state: present
  when:
    - inventory_hostname in groups[nt_cnodes]
    - enable_nfs_home

# echo "${sms_ip}:/opt/ohpc/pub /opt/ohpc/pub nfs nfsvers=3 0 0" >> $CHROOT/etc/fstab
- name: Add NFS client to mount /opt/ohpc/pub on a computing node
  ansible.posix.mount:
    name: "/opt/ohpc/pub"
    src: "{{ sms_ip }}{{ d_colon }}/opt/ohpc/pub"
    fstype: nfs
    state: present
  when:
    - inventory_hostname in groups[nt_cnodes]
    - enable_nfs_ohpc

# echo "/home *(rw,no_subtree_check,fsid=10,no_root_squash)" >> /etc/exports
- name: Export /home on master
  ansible.builtin.lineinfile:
    path: /etc/exports
    state: present
    backrefs: false
    regexp: '^/home \*\(rw,no_subtree_check,fsid=10,no_root_squash\)$'
    line: "/home *(rw,no_subtree_check,fsid=10,no_root_squash)"
  when:
    - inventory_hostname in groups[nt_sms]

# echo "/opt/ohpc/pub *(ro,no_subtree_check,fsid=11)" >> /etc/exports
- name: Export /opt/ohpc/pub on master
  ansible.builtin.lineinfile:
    path: /etc/exports
    state: present
    backrefs: false
    regexp: '^/opt/ohpc/pub \*\(ro,no_subtree_check,fsid=11\)$'
    line: "/opt/ohpc/pub *(ro,no_subtree_check,fsid=11)"
  when:
    - inventory_hostname in groups[nt_sms]
    - enable_nfs_ohpc

# helper for "Reload exportfs on master"
- name: Slurp current /etc/exports
  ansible.builtin.slurp:
    src: /etc/exports
  register: exports_file

# helper for "Reload exportfs on master"
- name: Decode and compare /etc/exports
  ansible.builtin.set_fact:
    exports_needs_reload: >-
      {{ (exports_file.content | b64decode).splitlines() | reject('match', '^#') | join('\n') | trim != desired_exports | trim }}

# exportfs -a
- name: Reload exportfs on master
  ansible.builtin.command: exportfs -a
  changed_when: exports_needs_reload
  when:
    - inventory_hostname in groups[nt_sms]

# systemctl restart nfs
- name: Restart nfs on a computing node
  ansible.builtin.service:
    name: nfs
    state: restarted
  when:
    - inventory_hostname in groups[nt_cnodes]

# systemctl enable nfs-server
- name: Enable nfs server on master
  ansible.builtin.service:
    name: nfs
    state: restarted
  when:
    - inventory_hostname in groups[nt_sms]

# systemctl start nfs-server
- name: Start nfs server on master
  ansible.builtin.service:
    name: nfs-server
    state: started
  when:
    - inventory_hostname in groups[nt_sms]
