---

# This file is distributed under the Apache License (the
# "License"); you may not use this file except in compliance
# with the License.  See the LICENSE file distributed with
# this work for additional information regarding copyright
# ownership.
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# This file is derived from recipe.sh in OpenHPC distribution
# and ported by Linaro Ltd. and Fujitsu Ltd.

#
# roles/ohpc-base/tasks/main.yml
#

# ------------------------------------------------------------
# Add baseline OpenHPC and provisioning services (Section 3.3)
# ------------------------------------------------------------
# yum -y groupinstall ohpc-base
- name: Install ohpc-base
  ansible.builtin.dnf:
    state: present
    name:
      - ohpc-base
  when:
    ( inventory_hostname in groups[nt_sms] ) or
    ( inventory_hostname in groups[nt_devnodes] ) or
    ( ( inventory_hostname in groups[nt_cnodes] ) and ( not enable_warewulf ) )

# yum -y --installroot=$CHROOT groupinstall ohpc-base-compute
- name: Install ohpc-base-compute for computing node images on master
  ansible.builtin.dnf:
    state: present
    installroot: "{{ compute_chroot_loc }}"
    name:
      - ohpc-base-compute
  when:
    - inventory_hostname in groups[nt_sms]
    - enable_warewulf

- name: Install ohpc-base-compute on computing nodes
  ansible.builtin.dnf:
    state: present
    name:
      - ohpc-base-compute
  when:
    - inventory_hostname in groups[nt_cnodes]
    - not enable_warewulf

# cp -p /etc/resolv.conf $CHROOT/etc/resolv.conf
- name: Copy /etc/resolv.conf to a computing node image on master
  ansible.builtin.copy:
    src: /etc/resolv.conf
    dest: "{{ compute_chroot_loc }}/etc/resolv.conf"
  when:
    - inventory_hostname in groups[nt_sms]
    - enable_warewulf

- name: Fetch /etc/resolv.conf in sms to a ansible local resolv.conf
  ansible.builtin.fetch:
    src: /etc/resolv.conf
    dest: "{{ role_path }}/resolv.conf"
    flat: true
  when:
    - inventory_hostname in groups[nt_sms]
    - not enable_warewulf

- name: Copy resolv.conf in ansible local on a computing node
  ansible.builtin.copy:
    src: "{{ role_path }}/resolv.conf"
    dest: /etc/resolv.conf
  when:
    - inventory_hostname in groups[nt_cnodes]
    - not enable_warewulf

- name: Remove resolv.conf on ansible local
  local_action: file path="{{ role_path }}/resolv.conf" state=absent
  become: false
  when:
    - inventory_hostname in groups[nt_sms]
    - not enable_warewulf

- name: Configure PDSH in bash.rc
  ansible.builtin.lineinfile:
    path: "{{ ansible_home }}/.bashrc"
    regexp: '^export PDSH_SSH_ARGS_APPEND=.*$'
    line: 'export PDSH_SSH_ARGS_APPEND="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /root/.ssh/cluster"'
    state: present
